"""
Blender Integration for Biomimetic Architecture
Integración con Blender para Arquitectura Biomimética

Genera archivos .blend con Geometry Nodes y shaders procedurales.
Generates .blend files with Geometry Nodes and procedural shaders.
"""

from typing import Dict, Optional
from ..core.composite import CompositePart


class BlenderBiomimeticExporter:
    """
    Exportador especializado para arquitectura biomimética en Blender.
    Specialized exporter for biomimetic architecture in Blender.
    """

    def __init__(self, mesh: CompositePart, config: Dict):
        """
        Inicializa el exportador / Initializes the exporter

        Args:
            mesh: Malla biomimética / Biomimetic mesh
            config: Configuración de escala / Scale configuration
        """
        self.mesh = mesh
        self.config = config

    def export(self, filepath: str, include_animation: bool = True,
              include_geometry_nodes: bool = True):
        """
        Exporta a script de Blender Python / Exports to Blender Python script

        Args:
            filepath: Ruta del archivo / File path
            include_animation: Si incluir animación de respiración / Whether to include breathing animation
            include_geometry_nodes: Si incluir Geometry Nodes / Whether to include Geometry Nodes
        """
        with open(filepath, 'w', encoding='utf-8') as f:
            # Encabezado / Header
            f.write("# Biomimetic Architecture for Blender\n")
            f.write("# Arquitectura Biomimética para Blender\n")
            f.write("# Generated by 3defect\n\n")

            f.write("import bpy\n")
            f.write("import math\n")
            f.write("from mathutils import Vector\n\n")

            # Limpiar escena / Clean scene
            f.write("# Limpiar escena / Clean scene\n")
            f.write("bpy.ops.object.select_all(action='SELECT')\n")
            f.write("bpy.ops.object.delete(use_global=False)\n\n")

            # Crear estructura base / Create base structure
            self._write_base_structure(f)

            # Añadir Geometry Nodes / Add Geometry Nodes
            if include_geometry_nodes:
                self._write_geometry_nodes(f)

            # Añadir shaders procedurales / Add procedural shaders
            self._write_procedural_shaders(f)

            # Añadir animación / Add animation
            if include_animation:
                self._write_breathing_animation(f)

            # Configurar iluminación / Setup lighting
            self._write_atmospheric_lighting(f)

            # Configurar render / Setup render
            self._write_render_settings(f)

        return filepath

    def _write_base_structure(self, f):
        """Escribe la estructura base del edificio / Writes base building structure"""
        f.write("# Estructura base / Base structure\n")
        f.write("def create_base_structure():\n")
        f.write("    # Crear forma base orgánica / Create organic base form\n")
        f.write("    bpy.ops.mesh.primitive_cylinder_add(radius=1, depth=2)\n")
        f.write("    base = bpy.context.active_object\n")
        f.write("    base.name = 'BiomimeticBase'\n")
        f.write(f"    base.scale = ({self.config['base_radius']}, "
                f"{self.config['base_radius']}, {self.config['height_range'][1]/2})\n")
        f.write("    return base\n\n")

        f.write("building_base = create_base_structure()\n\n")

    def _write_geometry_nodes(self, f):
        """Escribe Geometry Nodes para crecimiento fractal / Writes Geometry Nodes for fractal growth"""
        f.write("# Geometry Nodes para crecimiento fractal / Geometry Nodes for fractal growth\n")
        f.write("def setup_geometry_nodes(obj):\n")
        f.write("    # Añadir modificador Geometry Nodes / Add Geometry Nodes modifier\n")
        f.write("    mod = obj.modifiers.new('GeometryNodes', 'NODES')\n")
        f.write("    \n")
        f.write("    # Crear node tree / Create node tree\n")
        f.write("    node_tree = bpy.data.node_groups.new('BiomimeticGrowth', 'GeometryNodeTree')\n")
        f.write("    mod.node_group = node_tree\n")
        f.write("    \n")
        f.write("    # Añadir nodos / Add nodes\n")
        f.write("    nodes = node_tree.nodes\n")
        f.write("    \n")
        f.write("    # Input / Output\n")
        f.write("    input_node = nodes.new('NodeGroupInput')\n")
        f.write("    output_node = nodes.new('NodeGroupOutput')\n")
        f.write("    \n")
        f.write("    # Fractal pattern node / Nodo de patrón fractal\n")
        f.write("    subdivide = nodes.new('GeometryNodeSubdivideMesh')\n")
        f.write("    subdivide.inputs[1].default_value = 2  # Level\n")
        f.write("    \n")
        f.write("    # Organic deformation / Deformación orgánica\n")
        f.write("    noise = nodes.new('ShaderNodeTexNoise')\n")
        f.write("    noise.inputs['Scale'].default_value = 5.0\n")
        f.write("    \n")
        f.write("    # Connect nodes / Conectar nodos\n")
        f.write("    links = node_tree.links\n")
        f.write("    links.new(input_node.outputs[0], subdivide.inputs[0])\n")
        f.write("    links.new(subdivide.outputs[0], output_node.inputs[0])\n")
        f.write("    \n")
        f.write("    return node_tree\n\n")

        f.write("geo_nodes = setup_geometry_nodes(building_base)\n\n")

    def _write_procedural_shaders(self, f):
        """Escribe shaders procedurales / Writes procedural shaders"""
        f.write("# Shaders procedurales / Procedural shaders\n")
        f.write("def create_biomimetic_material():\n")
        f.write("    mat = bpy.data.materials.new('BiomimeticSkin')\n")
        f.write("    mat.use_nodes = True\n")
        f.write("    nodes = mat.node_tree.nodes\n")
        f.write("    links = mat.node_tree.links\n")
        f.write("    \n")
        f.write("    # Limpiar nodos / Clear nodes\n")
        f.write("    nodes.clear()\n")
        f.write("    \n")
        f.write("    # Output node\n")
        f.write("    output = nodes.new('ShaderNodeOutputMaterial')\n")
        f.write("    output.location = (400, 0)\n")
        f.write("    \n")
        f.write("    # Principled BSDF\n")
        f.write("    bsdf = nodes.new('ShaderNodeBsdfPrincipled')\n")
        f.write("    bsdf.location = (0, 0)\n")
        f.write("    bsdf.inputs['Base Color'].default_value = (0.9, 0.9, 0.85, 1.0)\n")
        f.write("    bsdf.inputs['Roughness'].default_value = 0.4\n")
        f.write("    bsdf.inputs['Subsurface'].default_value = 0.2  # Organic scattering\n")
        f.write("    \n")
        f.write("    # Noise texture para humedad / Noise texture for moisture\n")
        f.write("    noise = nodes.new('ShaderNodeTexNoise')\n")
        f.write("    noise.location = (-400, 0)\n")
        f.write("    noise.inputs['Scale'].default_value = 15.0\n")
        f.write("    \n")
        f.write("    # Color Ramp para controlar humedad / Color Ramp for moisture control\n")
        f.write("    ramp = nodes.new('ShaderNodeValToRGB')\n")
        f.write("    ramp.location = (-200, 0)\n")
        f.write("    \n")
        f.write("    # Conectar / Connect\n")
        f.write("    links.new(noise.outputs['Fac'], ramp.inputs['Fac'])\n")
        f.write("    links.new(ramp.outputs['Color'], bsdf.inputs['Roughness'])\n")
        f.write("    links.new(bsdf.outputs['BSDF'], output.inputs['Surface'])\n")
        f.write("    \n")
        f.write("    return mat\n\n")

        f.write("# Crear y asignar material / Create and assign material\n")
        f.write("bio_mat = create_biomimetic_material()\n")
        f.write("building_base.data.materials.append(bio_mat)\n\n")

    def _write_breathing_animation(self, f):
        """Escribe animación de respiración / Writes breathing animation"""
        f.write("# Animación de respiración / Breathing animation\n")
        f.write("def setup_breathing_animation(obj, duration=240):\n")
        f.write("    # Animar escala para simular respiración / Animate scale to simulate breathing\n")
        f.write("    \n")
        f.write("    # Frame 1: escala normal / Frame 1: normal scale\n")
        f.write("    obj.scale = (1.0, 1.0, 1.0)\n")
        f.write("    obj.keyframe_insert(data_path='scale', frame=1)\n")
        f.write("    \n")
        f.write("    # Frame medio: expansión / Mid frame: expansion\n")
        f.write("    mid_frame = duration // 2\n")
        f.write("    obj.scale = (1.02, 1.02, 1.01)\n")
        f.write("    obj.keyframe_insert(data_path='scale', frame=mid_frame)\n")
        f.write("    \n")
        f.write("    # Frame final: volver a normal / Final frame: back to normal\n")
        f.write("    obj.scale = (1.0, 1.0, 1.0)\n")
        f.write("    obj.keyframe_insert(data_path='scale', frame=duration)\n")
        f.write("    \n")
        f.write("    # Configurar interpolación suave / Setup smooth interpolation\n")
        f.write("    for fcurve in obj.animation_data.action.fcurves:\n")
        f.write("        for keyframe in fcurve.keyframe_points:\n")
        f.write("            keyframe.interpolation = 'BEZIER'\n")
        f.write("    \n")
        f.write("    # Hacer cíclico / Make cyclic\n")
        f.write("    for fcurve in obj.animation_data.action.fcurves:\n")
        f.write("        mod = fcurve.modifiers.new('CYCLES')\n\n")

        f.write("setup_breathing_animation(building_base)\n\n")

    def _write_atmospheric_lighting(self, f):
        """Escribe iluminación atmosférica / Writes atmospheric lighting"""
        f.write("# Iluminación atmosférica / Atmospheric lighting\n")
        f.write("def setup_atmospheric_lighting():\n")
        f.write("    # Sol / Sun\n")
        f.write("    bpy.ops.object.light_add(type='SUN', location=(0, 0, 50))\n")
        f.write("    sun = bpy.context.active_object\n")
        f.write("    sun.data.energy = 3.0\n")
        f.write("    sun.data.color = (1.0, 0.95, 0.8)  # Luz cálida / Warm light\n")
        f.write("    \n")
        f.write("    # Luz ambiente / Ambient light\n")
        f.write("    world = bpy.context.scene.world\n")
        f.write("    world.use_nodes = True\n")
        f.write("    bg = world.node_tree.nodes['Background']\n")
        f.write("    bg.inputs['Color'].default_value = (0.5, 0.7, 0.9, 1.0)  # Cielo azul / Blue sky\n")
        f.write("    bg.inputs['Strength'].default_value = 0.3\n\n")

        f.write("setup_atmospheric_lighting()\n\n")

    def _write_render_settings(self, f):
        """Escribe configuración de render / Writes render settings"""
        f.write("# Configuración de render / Render settings\n")
        f.write("def setup_render_settings():\n")
        f.write("    scene = bpy.context.scene\n")
        f.write("    \n")
        f.write("    # Cycles\n")
        f.write("    scene.render.engine = 'CYCLES'\n")
        f.write("    scene.cycles.samples = 128\n")
        f.write("    scene.cycles.use_denoising = True\n")
        f.write("    \n")
        f.write("    # Resolución / Resolution\n")
        f.write("    scene.render.resolution_x = 1920\n")
        f.write("    scene.render.resolution_y = 1080\n")
        f.write("    \n")
        f.write("    # Cámara / Camera\n")
        f.write("    bpy.ops.object.camera_add(location=(50, -50, 30))\n")
        f.write("    camera = bpy.context.active_object\n")
        f.write("    camera.rotation_euler = (1.1, 0, 0.785)\n")
        f.write("    scene.camera = camera\n\n")

        f.write("setup_render_settings()\n\n")

        f.write("print('Biomimetic architecture setup complete!')\n")
        f.write("print('¡Configuración de arquitectura biomimética completa!')\n")
