"""
Mesh Exporters / Exportadores de Malla

Exporta mallas biomiméticas a múltiples formatos.
Exports biomimetic meshes to multiple formats.
"""

import json
from typing import Dict, List, Tuple
from ..core.composite import CompositePart


class MeshExporter:
    """
    Exportador base para mallas / Base mesh exporter
    """
    
    def __init__(self, mesh: CompositePart):
        """
        Inicializa el exportador / Initializes the exporter
        
        Args:
            mesh: Malla a exportar / Mesh to export
        """
        self.mesh = mesh
        
    def _extract_geometry(self) -> Tuple[List, List, List]:
        """
        Extrae geometría de la malla.
        Extracts geometry from the mesh.
        
        Returns:
            Tupla de (vertices, faces, normals)
            Tuple of (vertices, faces, normals)
        """
        vertices = []
        faces = []
        normals = []
        
        # Simplificación: extraer posiciones de las partes
        # Simplification: extract positions from parts
        def extract_parts(part):
            """Recursively extract geometry from part and its sub-parts"""
            nonlocal vertices, faces, normals
            
            if hasattr(part, 'position'):
                pos = part.position
                vertices.append(pos)
                
            # Recursivamente extraer sub-partes / Recursively extract sub-parts
            if hasattr(part, 'parts'):
                # parts es una lista / parts is a list
                if isinstance(part.parts, list):
                    for sub_part in part.parts:
                        extract_parts(sub_part)
                # o un diccionario / or a dictionary
                elif isinstance(part.parts, dict):
                    for sub_part in part.parts.values():
                        extract_parts(sub_part)
            
        extract_parts(self.mesh)
        
        return vertices, faces, normals


class OBJExporter(MeshExporter):
    """
    Exportador a formato Wavefront OBJ / Wavefront OBJ format exporter
    """
    
    def export(self, filepath: str, include_materials: bool = True):
        """
        Exporta a formato OBJ / Exports to OBJ format
        
        Args:
            filepath: Ruta del archivo / File path
            include_materials: Si incluir archivo MTL / Whether to include MTL file
        """
        vertices, faces, normals = self._extract_geometry()
        
        with open(filepath, 'w') as f:
            # Encabezado / Header
            f.write("# Biomimetic Architecture Mesh\n")
            f.write("# Generated by 3defect\n\n")
            
            if include_materials:
                mtl_file = filepath.replace('.obj', '.mtl')
                f.write(f"mtllib {mtl_file.split('/')[-1]}\n\n")
                
            # Escribir vértices / Write vertices
            f.write("# Vertices\n")
            for i, v in enumerate(vertices):
                if isinstance(v, tuple) and len(v) >= 3:
                    f.write(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}\n")
                    
            # Escribir normales / Write normals
            if normals:
                f.write("\n# Normals\n")
                for n in normals:
                    f.write(f"vn {n[0]:.6f} {n[1]:.6f} {n[2]:.6f}\n")
                    
            # Escribir caras / Write faces
            if faces:
                f.write("\n# Faces\n")
                for face in faces:
                    f.write(f"f {' '.join(map(str, face))}\n")
                    
        if include_materials:
            self._export_mtl(mtl_file)
            
        return filepath
        
    def _export_mtl(self, filepath: str):
        """
        Exporta archivo de materiales MTL / Exports MTL material file
        """
        with open(filepath, 'w') as f:
            f.write("# Biomimetic Architecture Materials\n")
            f.write("# Generated by 3defect\n\n")
            
            # Material para piel / Skin material
            f.write("newmtl Skin\n")
            f.write("Ka 0.9 0.9 0.85\n")
            f.write("Kd 0.9 0.9 0.85\n")
            f.write("Ks 0.3 0.3 0.3\n")
            f.write("Ns 96\n\n")
            
            # Material para costillas / Ribs material
            f.write("newmtl Ribs\n")
            f.write("Ka 0.95 0.95 0.9\n")
            f.write("Kd 0.95 0.95 0.9\n")
            f.write("Ks 0.2 0.2 0.2\n")
            f.write("Ns 64\n\n")
            
            # Material para vegetación / Vegetation material
            f.write("newmtl Vegetation\n")
            f.write("Ka 0.3 0.8 0.4\n")
            f.write("Kd 0.3 0.8 0.4\n")
            f.write("Ks 0.1 0.1 0.1\n")
            f.write("Ns 32\n\n")
            
            # Material para vidrio / Glass material
            f.write("newmtl Glass\n")
            f.write("Ka 0.8 0.9 0.95\n")
            f.write("Kd 0.8 0.9 0.95\n")
            f.write("Ks 0.9 0.9 0.9\n")
            f.write("Ns 256\n")
            f.write("d 0.3\n")  # Transparencia / Transparency
            f.write("Tr 0.7\n")


class GLBExporter(MeshExporter):
    """
    Exportador a formato glTF/GLB / glTF/GLB format exporter
    """
    
    def export(self, filepath: str):
        """
        Exporta a formato GLB / Exports to GLB format
        
        Args:
            filepath: Ruta del archivo / File path
        """
        # Nota: Para exportación GLB real, se necesitaría una librería como pygltflib
        # Note: For real GLB export, would need a library like pygltflib
        
        # Por ahora, exportar especificación JSON compatible con glTF
        # For now, export JSON specification compatible with glTF
        
        gltf_spec = self._create_gltf_spec()
        
        json_path = filepath.replace('.glb', '.gltf')
        with open(json_path, 'w') as f:
            json.dump(gltf_spec, f, indent=2)
            
        return json_path
        
    def _create_gltf_spec(self) -> Dict:
        """
        Crea especificación glTF / Creates glTF specification
        """
        vertices, faces, normals = self._extract_geometry()
        
        return {
            "asset": {
                "version": "2.0",
                "generator": "3defect Biomimetic Architecture"
            },
            "scene": 0,
            "scenes": [{"nodes": [0]}],
            "nodes": [{"mesh": 0, "name": "BiomimeticBuilding"}],
            "meshes": [{
                "name": "BiomimeticMesh",
                "primitives": [{
                    "attributes": {
                        "POSITION": 0
                    },
                    "material": 0
                }]
            }],
            "materials": [
                {
                    "name": "Skin",
                    "pbrMetallicRoughness": {
                        "baseColorFactor": [0.9, 0.9, 0.85, 1.0],
                        "metallicFactor": 0.1,
                        "roughnessFactor": 0.4
                    }
                },
                {
                    "name": "Ribs",
                    "pbrMetallicRoughness": {
                        "baseColorFactor": [0.95, 0.95, 0.9, 1.0],
                        "metallicFactor": 0.0,
                        "roughnessFactor": 0.6
                    }
                },
                {
                    "name": "Vegetation",
                    "pbrMetallicRoughness": {
                        "baseColorFactor": [0.3, 0.8, 0.4, 1.0],
                        "metallicFactor": 0.0,
                        "roughnessFactor": 0.8
                    }
                },
                {
                    "name": "Glass",
                    "pbrMetallicRoughness": {
                        "baseColorFactor": [0.8, 0.9, 0.95, 0.3],
                        "metallicFactor": 0.0,
                        "roughnessFactor": 0.0
                    },
                    "alphaMode": "BLEND"
                }
            ]
        }


class FBXExporter(MeshExporter):
    """
    Exportador a formato FBX / FBX format exporter
    """
    
    def export(self, filepath: str):
        """
        Exporta a formato FBX / Exports to FBX format
        
        Args:
            filepath: Ruta del archivo / File path
        """
        # Nota: Exportación FBX real requiere librerías específicas
        # Note: Real FBX export requires specific libraries
        
        # Por ahora, crear un archivo de texto con especificación
        # For now, create a text file with specification
        
        vertices, faces, normals = self._extract_geometry()
        
        with open(filepath, 'w') as f:
            f.write("; FBX 7.4.0 project file\n")
            f.write("; Generated by 3defect Biomimetic Architecture\n\n")
            
            f.write("FBXHeaderExtension:  {\n")
            f.write("    FBXHeaderVersion: 1003\n")
            f.write("    FBXVersion: 7400\n")
            f.write("    CreationTimeStamp:  {\n")
            f.write("        Version: 1000\n")
            f.write("    }\n")
            f.write("}\n\n")
            
            f.write("; Object definitions\n")
            f.write("Definitions:  {\n")
            f.write("    Version: 100\n")
            f.write("    Count: 1\n")
            f.write("}\n\n")
            
            f.write("; Object properties\n")
            f.write("Objects:  {\n")
            f.write("    Geometry: 1001, \"Geometry::\", \"Mesh\" {\n")
            f.write(f"        Vertices: *{len(vertices) * 3} {{\n")
            
            for v in vertices:
                if isinstance(v, tuple) and len(v) >= 3:
                    f.write(f"            a: {v[0]},{v[1]},{v[2]}\n")
                    
            f.write("        }\n")
            f.write("    }\n")
            f.write("}\n")
            
        return filepath


def export_mesh(mesh: CompositePart, filepath: str, format: str = "obj",
               include_materials: bool = True):
    """
    Exporta malla a formato especificado.
    Exports mesh to specified format.
    
    Args:
        mesh: Malla a exportar / Mesh to export
        filepath: Ruta del archivo / File path
        format: Formato ("obj", "fbx", "glb") / Format ("obj", "fbx", "glb")
        include_materials: Si incluir materiales / Whether to include materials
        
    Returns:
        Ruta del archivo exportado / Path to exported file
    """
    exporters = {
        "obj": OBJExporter,
        "fbx": FBXExporter,
        "glb": GLBExporter,
    }
    
    if format not in exporters:
        raise ValueError(f"Formato no soportado / Unsupported format: {format}")
        
    exporter_class = exporters[format]
    exporter = exporter_class(mesh)
    
    if format == "obj":
        return exporter.export(filepath, include_materials)
    else:
        return exporter.export(filepath)
