"""Blender script generator for reference-matched vehicles.

This module does not import bpy. It produces a standalone Blender Python
script so it remains importable and testable on normal Python installations.
"""

from pprint import pformat


def generate_p911_reference_script(vehicle) -> str:
    """Generate a Blender Python script for a first-pass P911 silhouette."""
    data = vehicle.to_dict()
    resolved = data["resolved"]
    wheels = data["wheel_centers"]

    payload = pformat(
        {"resolved": resolved, "wheel_centers": wheels},
        width=100,
        sort_dicts=True,
    )

    return f'''"""Generated by 3defect for P911_REF_001."""
import bpy
import math

DATA = {payload}
R = DATA["resolved"]
W = DATA["wheel_centers"]


def clear_scene():
    bpy.ops.object.select_all(action="SELECT")
    bpy.ops.object.delete(use_global=False)


def mat(name, rgba, metallic=0.0, roughness=0.35):
    material = bpy.data.materials.new(name=name)
    material.use_nodes = True
    bsdf = material.node_tree.nodes.get("Principled BSDF")
    bsdf.inputs["Base Color"].default_value = rgba
    bsdf.inputs["Metallic"].default_value = metallic
    bsdf.inputs["Roughness"].default_value = roughness
    return material


def add_uv(name, location, scale, material, segments=48):
    bpy.ops.mesh.primitive_uv_sphere_add(
        segments=segments, ring_count=24, location=location
    )
    obj = bpy.context.object
    obj.name = name
    obj.scale = scale
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    obj.data.materials.append(material)
    bpy.ops.object.shade_smooth()
    return obj


def add_box(name, location, scale, material, bevel=0.08):
    bpy.ops.mesh.primitive_cube_add(size=1.0, location=location)
    obj = bpy.context.object
    obj.name = name
    obj.scale = scale
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    modifier = obj.modifiers.new(name="Bevel", type="BEVEL")
    modifier.width = bevel
    modifier.segments = 3
    obj.data.materials.append(material)
    return obj


def add_wheel(name, location, radius, width, tire_mat, rim_mat):
    bpy.ops.mesh.primitive_torus_add(
        major_radius=radius * 0.78,
        minor_radius=radius * 0.22,
        major_segments=48,
        minor_segments=16,
        location=location,
        rotation=(math.radians(90), 0, 0),
    )
    tire = bpy.context.object
    tire.name = name + "_TIRE"
    tire.scale.y = width / max(radius * 0.44, 0.001)
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    tire.data.materials.append(tire_mat)
    bpy.ops.object.shade_smooth()

    bpy.ops.mesh.primitive_cylinder_add(
        vertices=32,
        radius=radius * 0.58,
        depth=width * 0.78,
        location=location,
        rotation=(math.radians(90), 0, 0),
    )
    rim = bpy.context.object
    rim.name = name + "_RIM"
    rim.data.materials.append(rim_mat)
    return tire, rim


def build():
    clear_scene()

    body_mat = mat("Body_Red", (*R["body_color"], 1.0), metallic=0.15, roughness=0.22)
    glass_mat = mat("Glass", (0.03, 0.045, 0.05, 1.0), metallic=0.05, roughness=0.12)
    black_mat = mat("Black", (0.012, 0.012, 0.012, 1.0), roughness=0.28)
    rim_mat = mat("Rim", (0.08, 0.08, 0.085, 1.0), metallic=0.8, roughness=0.2)
    lamp_mat = mat("Lamp", (0.72, 0.68, 0.56, 1.0), metallic=0.0, roughness=0.18)

    length = R["length"]
    width = R["width"]
    height = R["height"]
    gc = R["ground_clearance"]

    # Main lower body: intentionally broad and low to match the supplied image.
    add_uv(
        "BODY_main_shell",
        (0.0, 0.0, gc + height * 0.36),
        (length * 0.50, width * 0.50, height * 0.31),
        body_mat,
    )

    # Hood / nose volume.
    add_uv(
        "BODY_hood",
        (length * 0.29, 0.0, gc + height * 0.42),
        (length * 0.23, width * 0.47, height * 0.16),
        body_mat,
    )

    # Cabin volume.
    add_uv(
        "BODY_roof",
        (-length * 0.06, 0.0, gc + height * 0.72),
        (length * 0.27, width * 0.37, height * 0.29),
        body_mat,
    )

    # Dark glazing envelope nested inside the cabin.
    add_uv(
        "WINDOWS_glass_envelope",
        (-length * 0.055, 0.0, gc + height * 0.735),
        (length * 0.245, width * 0.345, height * 0.245),
        glass_mat,
    )

    # Fender masses.
    for key in ("FL", "FR"):
        x, y, z = W[key]
        add_uv(
            "FENDER_" + key,
            (x, y, z * 1.02),
            (
                R["wheel_radius_front"] * 1.16,
                R["front_fender_bulge"] * 2.6,
                R["wheel_radius_front"] * 1.08,
            ),
            body_mat,
        )

    for key in ("RL", "RR"):
        x, y, z = W[key]
        add_uv(
            "FENDER_" + key,
            (x, y, z * 1.03),
            (
                R["wheel_radius_rear"] * 1.22,
                R["rear_fender_bulge"] * 2.6,
                R["wheel_radius_rear"] * 1.12,
            ),
            body_mat,
        )

    # Wheels.
    for key in ("FL", "FR"):
        add_wheel(
            "WHEEL_" + key,
            W[key],
            R["wheel_radius_front"],
            R["wheel_width_front"],
            black_mat,
            rim_mat,
        )
    for key in ("RL", "RR"):
        add_wheel(
            "WHEEL_" + key,
            W[key],
            R["wheel_radius_rear"],
            R["wheel_width_rear"],
            black_mat,
            rim_mat,
        )

    # Front bumper / splitter.
    add_box(
        "FRONT_bumper",
        (length * 0.47, 0.0, gc + height * 0.20),
        (length * 0.055, width * 0.47, height * 0.12),
        body_mat,
        bevel=0.06,
    )
    add_box(
        "FRONT_splitter",
        (length * 0.50, 0.0, gc * 0.75),
        (R["splitter_depth"], width * 0.51, R["splitter_height"]),
        black_mat,
        bevel=0.025,
    )

    # Headlights.
    for side in (-1.0, 1.0):
        add_uv(
            "LIGHT_headlight",
            (length * 0.405, side * width * 0.31, gc + height * 0.53),
            (R["headlight_radius"] * 0.62, R["headlight_radius"], R["headlight_radius"]),
            lamp_mat,
        )

    # Rear wing.
    add_box(
        "AERO_rear_wing",
        (-length * 0.43, 0.0, gc + height * 0.87),
        (R["wing_depth"] * 0.50, R["wing_width"] * 0.50, 0.035),
        body_mat,
        bevel=0.035,
    )
    for side in (-1.0, 1.0):
        add_box(
            "AERO_wing_support",
            (-length * 0.38, side * R["wing_width"] * 0.35, gc + height * 0.70),
            (0.045, 0.035, R["wing_height"] * 0.45),
            black_mat,
            bevel=0.02,
        )

    # Ground plane.
    bpy.ops.mesh.primitive_plane_add(size=30, location=(0, 0, 0))
    ground = bpy.context.object
    ground.name = "GROUND"
    ground.data.materials.append(mat("Ground", (0.54, 0.43, 0.30, 1.0), roughness=0.6))

    # Camera: front three-quarter angle similar to the reference.
    bpy.ops.object.camera_add(location=(6.4, -7.0, 3.6))
    camera = bpy.context.object
    camera.name = "CAM_reference_3q"
    bpy.context.scene.camera = camera

    direction = mathutils.Vector((0.0, 0.0, height * 0.42)) - camera.location
    camera.rotation_euler = direction.to_track_quat("-Z", "Y").to_euler()
    camera.data.lens = 58

    # Lighting.
    bpy.ops.object.light_add(type="AREA", location=(3.5, -3.5, 6.0))
    key = bpy.context.object
    key.data.energy = 1100
    key.data.shape = "DISK"
    key.data.size = 5.0

    bpy.ops.object.light_add(type="AREA", location=(-4.0, 2.0, 4.0))
    fill = bpy.context.object
    fill.data.energy = 650
    fill.data.size = 4.0

    scene = bpy.context.scene
    scene.render.resolution_x = 1080
    scene.render.resolution_y = 810
    scene.render.resolution_percentage = 100


if __name__ == "__main__":
    import mathutils
    build()
'''
